jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and Deploy Pages
        uses: actions/jekyll-build-pages@v1
        with:
          source: docs      # <-- must exactly match the folder name with your site files
          destination: docs/_site
