name: R-CMD-check

on:
  push:
  branches: [main]
pull_request:
  branches: [main]

jobs:
  R-CMD-check:
  runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@v3

- uses: r-lib/actions/setup-r@v2

- name: Install dependencies
uses: r-lib/actions/setup-r-dependencies@v2
with:
  extra-packages: |
  any::rcmdcheck
any::pkgdown
any::knitr
any::rmarkdown
needs: check

- name: Check
uses: r-lib/actions/check-r-package@v2
