name: R-CMD-check
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            devtools
            roxygen2
            pkgdown
      - name: Session info
        run: sessionInfo()
        shell: Rscript {0}
      - name: Check package
        run: |
          devtools::document()
          devtools::build_vignettes()
          devtools::check(vignettes = TRUE, error_on = "error")
        shell: Rscript {0}
